"""add other relationships

Revision ID: 257ecba9249c
Revises: f1c9de1cf332
Create Date: 2022-10-24 18:54:45.179535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '257ecba9249c'
down_revision = 'f1c9de1cf332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('med_diagnostics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('med_imageries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('med_labtests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('med_surgeries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('survival_rate', sa.Float(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('med_therapies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rx_line',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('qsp', sa.String(), nullable=True),
    sa.Column('boxes', sa.Integer(), nullable=True),
    sa.Column('dosage', sa.String(), nullable=True),
    sa.Column('ailments', sa.String(), nullable=True),
    sa.Column('medication_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificaions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('observations', sa.String(), nullable=True),
    sa.Column('ailments', sa.String(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ordinances')
    op.drop_table('medexams')
    op.drop_table('medtests')
    op.add_column('admissions', sa.Column('genre', sa.String(), nullable=True))
    op.add_column('admissions', sa.Column('cause', sa.String(), nullable=True))
    op.drop_column('admissions', 'motif')
    op.add_column('consultations', sa.Column('doctor_id', sa.Integer(), nullable=True))
    op.add_column('consultations', sa.Column('patient_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'consultations', 'users', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'consultations', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.add_column('medications', sa.Column('alternatives', sa.String(), nullable=True))
    op.add_column('medications', sa.Column('ailments', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('peculiarities', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('allergies', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('history', sa.String(), nullable=True))
    op.drop_column('patients', 'peculiarity')
    op.drop_column('patients', 'patient_history')
    op.add_column('prescriptions', sa.Column('date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('prescriptions', sa.Column('reference', sa.String(), nullable=True))
    op.add_column('prescriptions', sa.Column('history', sa.String(), nullable=True))
    op.add_column('prescriptions', sa.Column('doctor_id', sa.Integer(), nullable=True))
    op.add_column('prescriptions', sa.Column('patient_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'prescriptions', 'users', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'prescriptions', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_column('prescriptions', 'boxes')
    op.drop_column('prescriptions', 'dosage')
    op.drop_column('prescriptions', 'qsp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescriptions', sa.Column('qsp', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('prescriptions', sa.Column('dosage', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('prescriptions', sa.Column('boxes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.drop_column('prescriptions', 'patient_id')
    op.drop_column('prescriptions', 'doctor_id')
    op.drop_column('prescriptions', 'history')
    op.drop_column('prescriptions', 'reference')
    op.drop_column('prescriptions', 'date')
    op.add_column('patients', sa.Column('patient_history', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('peculiarity', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('patients', 'history')
    op.drop_column('patients', 'allergies')
    op.drop_column('patients', 'peculiarities')
    op.drop_column('medications', 'ailments')
    op.drop_column('medications', 'alternatives')
    op.drop_constraint(None, 'consultations', type_='foreignkey')
    op.drop_constraint(None, 'consultations', type_='foreignkey')
    op.drop_column('consultations', 'patient_id')
    op.drop_column('consultations', 'doctor_id')
    op.add_column('admissions', sa.Column('motif', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('admissions', 'cause')
    op.drop_column('admissions', 'genre')
    op.create_table('medtests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duration', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='medtests_pkey')
    )
    op.create_table('medexams',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date_asked', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('date_run', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('date_received', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('result', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('units', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('interval', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='medexams_pkey')
    )
    op.create_table('ordinances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('reference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('antecedents', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ordinances_pkey')
    )
    op.drop_table('certificaions')
    op.drop_table('rx_line')
    op.drop_table('med_therapies')
    op.drop_table('med_surgeries')
    op.drop_table('med_labtests')
    op.drop_table('med_imageries')
    op.drop_table('med_diagnostics')
    # ### end Alembic commands ###
