"""update gen models

Revision ID: 4d19ea600af6
Revises: 14be25b877e1
Create Date: 2022-10-28 16:09:58.708028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d19ea600af6'
down_revision = '14be25b877e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('med_tests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('med_labtests')
    op.add_column('med_diagnostics', sa.Column('description', sa.String(), nullable=True))
    op.add_column('med_diagnostics', sa.Column('sessions', sa.String(), nullable=True))
    op.alter_column('med_diagnostics', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('med_imageries', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('med_imageries', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('med_imageries', 'duration')
    op.add_column('med_surgeries', sa.Column('description', sa.String(), nullable=True))
    op.add_column('med_surgeries', sa.Column('anaestesia_genre', sa.String(), nullable=True))
    op.alter_column('med_surgeries', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('med_surgeries', 'cost',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('med_therapies', sa.Column('description', sa.String(), nullable=True))
    op.add_column('med_therapies', sa.Column('sessions', sa.Integer(), nullable=True))
    op.alter_column('med_therapies', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('med_therapies', 'cost',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('medications', 'maker',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('medications', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medications', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('medications', 'maker',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('med_therapies', 'cost',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('med_therapies', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('med_therapies', 'sessions')
    op.drop_column('med_therapies', 'description')
    op.alter_column('med_surgeries', 'cost',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('med_surgeries', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('med_surgeries', 'anaestesia_genre')
    op.drop_column('med_surgeries', 'description')
    op.add_column('med_imageries', sa.Column('duration', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('med_imageries', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('med_imageries', 'description')
    op.alter_column('med_diagnostics', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('med_diagnostics', 'sessions')
    op.drop_column('med_diagnostics', 'description')
    op.create_table('med_labtests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duration', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='med_labtests_pkey')
    )
    op.drop_table('med_tests')
    # ### end Alembic commands ###
