"""update models

Revision ID: 4fd1435834ee
Revises: 5f787dfb5b88
Create Date: 2022-10-27 11:48:09.688551

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4fd1435834ee'
down_revision = '5f787dfb5b88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admissions', sa.Column('is_pending', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('consultations', sa.Column('is_pending', sa.Boolean(), server_default='True', nullable=False))
    op.alter_column('consultations', 'diagnosis',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('consultations', 'weight',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('consultations', 'height',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('consultations', 'temperature',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('consultations', 'systole',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('consultations', 'diastole',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('consultations', 'oxymetry',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('consultations', 'bmi',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('consultations', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('consultations', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('medical_records', sa.Column('current_state', sa.String(), nullable=True))
    op.drop_column('medical_records', 'observations')
    op.drop_column('medical_records', 'history')
    op.add_column('users', sa.Column('subrole_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'subroles', ['subrole_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'subrole_id')
    op.add_column('medical_records', sa.Column('history', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('medical_records', sa.Column('observations', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('medical_records', 'current_state')
    op.alter_column('consultations', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('consultations', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('consultations', 'bmi',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('consultations', 'oxymetry',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('consultations', 'diastole',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('consultations', 'systole',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('consultations', 'temperature',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('consultations', 'height',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('consultations', 'weight',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('consultations', 'diagnosis',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('consultations', 'is_pending')
    op.drop_column('admissions', 'is_pending')
    # ### end Alembic commands ###
