"""update insurance tiers

Revision ID: 5d131c6842e0
Revises: b5b8164a62cc
Create Date: 2023-02-21 20:38:23.075618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d131c6842e0'
down_revision = 'b5b8164a62cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insurance_tiers', sa.Column('overview', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insurance_tiers', 'overview')
    # ### end Alembic commands ###
