"""update relationships

Revision ID: 5e8f5b5f9372
Revises: dc2ee3313e01
Create Date: 2022-10-27 08:28:56.442600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e8f5b5f9372'
down_revision = 'dc2ee3313e01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_on', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('allergies', sa.String(), nullable=True),
    sa.Column('ailments', sa.String(), nullable=True),
    sa.Column('treatments', sa.String(), nullable=True),
    sa.Column('tests', sa.String(), nullable=True),
    sa.Column('observations', sa.String(), nullable=True),
    sa.Column('history', sa.String(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('rx_line', sa.Column('prescription_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rx_line', 'prescriptions', ['prescription_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rx_line', type_='foreignkey')
    op.drop_column('rx_line', 'prescription_id')
    op.drop_table('medical_records')
    op.drop_table('pharmacies')
    # ### end Alembic commands ###
