"""add new tables

Revision ID: 5f787dfb5b88
Revises: 5e8f5b5f9372
Create Date: 2022-10-27 10:10:16.891593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f787dfb5b88'
down_revision = '5e8f5b5f9372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
