"""update fin  models

Revision ID: 63113af827d4
Revises: 774b1ee10bff
Create Date: 2023-02-13 11:17:04.243415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63113af827d4'
down_revision = '774b1ee10bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('momo_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('carrier', sa.String(), nullable=False),
    sa.Column('overview', sa.String(), nullable=True),
    sa.Column('credit', sa.Integer(), nullable=True),
    sa.Column('debit', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('other_mobile_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('persona', sa.String(), nullable=True),
    sa.Column('fullname', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('motive', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('paid', sa.Integer(), nullable=True),
    sa.Column('due', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('momo_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['transaction_genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['momo_id'], ['momo_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_mobile_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('paid', sa.Integer(), nullable=True),
    sa.Column('due', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('momo_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['transaction_genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['momo_id'], ['momo_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('momo_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['momo_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_mobile_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('overview', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('paid', sa.Integer(), nullable=True),
    sa.Column('due', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('momo_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['transaction_genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['momo_id'], ['momo_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bank_comments', sa.Column('account_id', sa.Integer(), nullable=True))
    op.drop_constraint('bank_comments_title_key', 'bank_comments', type_='unique')
    op.create_foreign_key(None, 'bank_comments', 'banks', ['account_id'], ['id'], ondelete='CASCADE')
    op.add_column('cashdesk_comments', sa.Column('account_id', sa.Integer(), nullable=True))
    op.drop_constraint('cashdesk_comments_title_key', 'cashdesk_comments', type_='unique')
    op.create_foreign_key(None, 'cashdesk_comments', 'cashdesks', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_column('cashdesks', 'commentary')
    op.drop_constraint('companies_insurance_id_fkey', 'companies', type_='foreignkey')
    op.create_foreign_key(None, 'companies', 'insurances', ['insurance_id'], ['id'], ondelete='CASCADE')
    op.alter_column('insurance_tiers', 'insurance_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('insurance_tiers_insurance_id_fkey', 'insurance_tiers', type_='foreignkey')
    op.create_foreign_key(None, 'insurance_tiers', 'insurances', ['insurance_id'], ['id'], ondelete='CASCADE')
    op.add_column('medical_records', sa.Column('peculiarity', sa.String(), nullable=True))
    op.drop_column('medical_records', 'current_state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('current_state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('medical_records', 'peculiarity')
    op.drop_constraint(None, 'insurance_tiers', type_='foreignkey')
    op.create_foreign_key('insurance_tiers_insurance_id_fkey', 'insurance_tiers', 'insurances', ['insurance_id'], ['id'])
    op.alter_column('insurance_tiers', 'insurance_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.create_foreign_key('companies_insurance_id_fkey', 'companies', 'insurances', ['insurance_id'], ['id'])
    op.add_column('cashdesks', sa.Column('commentary', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cashdesk_comments', type_='foreignkey')
    op.create_unique_constraint('cashdesk_comments_title_key', 'cashdesk_comments', ['title'])
    op.drop_column('cashdesk_comments', 'account_id')
    op.drop_constraint(None, 'bank_comments', type_='foreignkey')
    op.create_unique_constraint('bank_comments_title_key', 'bank_comments', ['title'])
    op.drop_column('bank_comments', 'account_id')
    op.drop_table('user_mobile_transactions')
    op.drop_table('momo_comments')
    op.drop_table('patient_mobile_transactions')
    op.drop_table('other_mobile_transactions')
    op.drop_table('momo_accounts')
    # ### end Alembic commands ###
