"""update specialty model

Revision ID: 652a9b47dc3d
Revises: 87f307186aa6
Create Date: 2023-01-28 08:47:49.611699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '652a9b47dc3d'
down_revision = '87f307186aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specialties', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('specialties', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'specialties', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'specialties', type_='unique')
    op.alter_column('specialties', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('specialties', 'description')
    # ### end Alembic commands ###
