"""update patient models

Revision ID: 6934b58a13f9
Revises: 9c3f79b411f6
Create Date: 2022-10-27 13:28:07.042499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6934b58a13f9'
down_revision = '9c3f79b411f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'weight',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('patients', 'height',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('patients', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('patients', 'tel',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('patients', 'cel',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'cel',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('patients', 'tel',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('patients', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('patients', 'height',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('patients', 'weight',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
