"""update pharmacy models

Revision ID: 6a7245dd5825
Revises: 3f6035a28a2f
Create Date: 2023-01-09 11:43:53.803706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a7245dd5825'
down_revision = '3f6035a28a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('external_rx',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prescriptions', sa.String(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rx_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('qsp', sa.String(), nullable=True),
    sa.Column('boxes', sa.Integer(), nullable=True),
    sa.Column('dosage', sa.String(), nullable=True),
    sa.Column('ailments', sa.String(), nullable=True),
    sa.Column('medication_id', sa.Integer(), nullable=True),
    sa.Column('prescription_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('rx_line')
    op.add_column('accessories', sa.Column('lot_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'accessories', 'lots', ['lot_id'], ['id'], ondelete='CASCADE')
    op.add_column('medications', sa.Column('lot_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'medications', 'lots', ['lot_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medications', type_='foreignkey')
    op.drop_column('medications', 'lot_id')
    op.drop_constraint(None, 'accessories', type_='foreignkey')
    op.drop_column('accessories', 'lot_id')
    op.create_table('rx_line',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('qsp', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('boxes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dosage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ailments', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('medication_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prescription_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], name='rx_line_medication_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], name='rx_line_prescription_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='rx_line_pkey')
    )
    op.drop_table('rx_lines')
    op.drop_table('external_rx')
    op.drop_table('lots')
    # ### end Alembic commands ###
