"""update  models

Revision ID: 6c406a0e1771
Revises: eb14391dba1e
Create Date: 2022-12-20 20:12:32.335950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c406a0e1771'
down_revision = 'eb14391dba1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('types_of_consultations',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('parameters', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('patients', sa.Column(
        'civil_status', sa.String(), nullable=True))
    op.drop_column('patients', 'history')
    op.drop_column('patients', 'matrimony')
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('tel', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cel', sa.String(), nullable=True))
    op.add_column('users', sa.Column('languages', sa.String(), nullable=True))
    op.add_column('users', sa.Column(
        'closed_cases', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('experience', sa.Integer(),
                  server_default='0', nullable=True))
    op.drop_constraint('users_phone_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['tel'])
    op.create_unique_constraint(None, 'users', ['cel'])
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.VARCHAR(),
                  autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_phone_key', 'users', ['phone'])
    op.drop_column('users', 'experience')
    op.drop_column('users', 'closed_cases')
    op.drop_column('users', 'languages')
    op.drop_column('users', 'cel')
    op.drop_column('users', 'tel')
    op.drop_column('users', 'age')
    op.add_column('patients', sa.Column(
        'matrimony', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column(
        'history', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('patients', 'civil_status')
    op.drop_table('types_of_consultations')
    # ### end Alembic commands ###
