"""add comodity model

Revision ID: 74f662f05c5e
Revises: 9f607dc99e15
Create Date: 2023-02-21 10:49:52.280498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '74f662f05c5e'
down_revision = '9f607dc99e15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comodities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date_added', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bills', sa.Column('comodity_id', sa.Integer(), nullable=True))
    op.add_column('bills', sa.Column('insurance_tier_id', sa.Integer(), server_default='0', nullable=True))
    op.create_foreign_key(None, 'bills', 'comodities', ['comodity_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bills', 'insurance_tiers', ['insurance_tier_id'], ['id'], ondelete='CASCADE')
    op.alter_column('insurance_tiers', 'percentage',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('insurance_tiers', 'ceiling',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('insurance_tiers', 'custom_price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.add_column('patient_bank_transactions', sa.Column('comodity_id', sa.Integer(), nullable=True))
    op.add_column('patient_bank_transactions', sa.Column('insurance_tier_id', sa.Integer(), server_default='0', nullable=True))
    op.create_foreign_key(None, 'patient_bank_transactions', 'insurance_tiers', ['insurance_tier_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'patient_bank_transactions', 'comodities', ['comodity_id'], ['id'], ondelete='CASCADE')
    op.add_column('patient_cash_transactions', sa.Column('comodity_id', sa.Integer(), nullable=True))
    op.add_column('patient_cash_transactions', sa.Column('insurance_tier_id', sa.Integer(), server_default='0', nullable=True))
    op.create_foreign_key(None, 'patient_cash_transactions', 'insurance_tiers', ['insurance_tier_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'patient_cash_transactions', 'comodities', ['comodity_id'], ['id'], ondelete='CASCADE')
    op.add_column('patient_mobile_transactions', sa.Column('comodity_id', sa.Integer(), nullable=True))
    op.add_column('patient_mobile_transactions', sa.Column('insurance_tier_id', sa.Integer(), server_default='0', nullable=True))
    op.create_foreign_key(None, 'patient_mobile_transactions', 'insurance_tiers', ['insurance_tier_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'patient_mobile_transactions', 'comodities', ['comodity_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patient_mobile_transactions', type_='foreignkey')
    op.drop_constraint(None, 'patient_mobile_transactions', type_='foreignkey')
    op.drop_column('patient_mobile_transactions', 'insurance_tier_id')
    op.drop_column('patient_mobile_transactions', 'comodity_id')
    op.drop_constraint(None, 'patient_cash_transactions', type_='foreignkey')
    op.drop_constraint(None, 'patient_cash_transactions', type_='foreignkey')
    op.drop_column('patient_cash_transactions', 'insurance_tier_id')
    op.drop_column('patient_cash_transactions', 'comodity_id')
    op.drop_constraint(None, 'patient_bank_transactions', type_='foreignkey')
    op.drop_constraint(None, 'patient_bank_transactions', type_='foreignkey')
    op.drop_column('patient_bank_transactions', 'insurance_tier_id')
    op.drop_column('patient_bank_transactions', 'comodity_id')
    op.alter_column('insurance_tiers', 'custom_price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('insurance_tiers', 'ceiling',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('insurance_tiers', 'percentage',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_constraint(None, 'bills', type_='foreignkey')
    op.drop_constraint(None, 'bills', type_='foreignkey')
    op.drop_column('bills', 'insurance_tier_id')
    op.drop_column('bills', 'comodity_id')
    op.drop_table('comodities')
    # ### end Alembic commands ###
