"""update models

Revision ID: 80bbc6d6fdea
Revises: f9651d8e4e6d
Create Date: 2023-01-25 11:30:57.205205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80bbc6d6fdea'
down_revision = 'f9651d8e4e6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statuses',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('prescriptions', sa.Column(
        'note', sa.String(), nullable=True))
    op.add_column('prescriptions', sa.Column(
        'treatment', sa.String(), nullable=True))
    op.add_column('prescriptions', sa.Column(
        'status', sa.String(), nullable=True))
    op.drop_column('prescriptions', 'reference')
    op.drop_column('prescriptions', 'history')
    op.add_column('rooms', sa.Column('price', sa.Integer(), nullable=True))
    op.alter_column('rooms', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.drop_column('rooms', 'cost')
    op.alter_column('specialties', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('specialties', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.add_column('rooms', sa.Column('cost', sa.INTEGER(),
                  autoincrement=False, nullable=True))
    op.alter_column('rooms', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.drop_column('rooms', 'price')
    op.add_column('prescriptions', sa.Column(
        'history', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('prescriptions', sa.Column(
        'reference', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('prescriptions', 'status')
    op.drop_column('prescriptions', 'treatment')
    op.drop_column('prescriptions', 'note')
    op.drop_table('statuses')
    # ### end Alembic commands ###
