"""update consultation models

Revision ID: 8119ccdc8046
Revises: 6c406a0e1771
Create Date: 2023-01-06 11:10:28.387807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8119ccdc8046'
down_revision = '6c406a0e1771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultation_genres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parameters', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('types_of_consultations')
    op.add_column('consultations', sa.Column('genre_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'consultations', 'consultation_genres', ['genre_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'consultations', type_='foreignkey')
    op.drop_column('consultations', 'genre_id')
    op.create_table('types_of_consultations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('parameters', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='types_of_consultations_pkey')
    )
    op.drop_table('consultation_genres')
    # ### end Alembic commands ###
