"""update room model

Revision ID: 87f307186aa6
Revises: 80bbc6d6fdea
Create Date: 2023-01-27 07:40:40.221864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87f307186aa6'
down_revision = '80bbc6d6fdea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('beds', sa.Integer(), server_default='0', nullable=True))
    op.alter_column('rooms', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('rooms', 'beds')
    # ### end Alembic commands ###
