"""add specialty model

Revision ID: 9b302dbcd4e0
Revises: 870f1c484681
Create Date: 2022-11-07 10:40:11.745918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b302dbcd4e0'
down_revision = '870f1c484681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('ordinances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicaments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('qsp', sa.String(), nullable=True),
    sa.Column('boxes', sa.Integer(), nullable=True),
    sa.Column('dosage', sa.String(), nullable=True),
    sa.Column('ailments', sa.String(), nullable=True),
    sa.Column('medication', sa.String(), nullable=True),
    sa.Column('ordinance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ordinance_id'], ['ordinances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('admissions', 'cause',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admissions', 'cause',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('medicaments')
    op.drop_table('ordinances')
    op.drop_table('specialties')
    # ### end Alembic commands ###
