"""standardise transaction models

Revision ID: b5b8164a62cc
Revises: 77dbc4ff8d85
Create Date: 2023-02-21 17:00:41.247981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b8164a62cc'
down_revision = '77dbc4ff8d85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_genres')
    op.add_column('patient_bank_transactions', sa.Column('overview', sa.String(), nullable=True))
    op.drop_column('patient_bank_transactions', 'description')
    op.add_column('patient_cash_transactions', sa.Column('overview', sa.String(), nullable=True))
    op.drop_column('patient_cash_transactions', 'description')
    op.add_column('patient_mobile_transactions', sa.Column('overview', sa.String(), nullable=True))
    op.drop_column('patient_mobile_transactions', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_mobile_transactions', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('patient_mobile_transactions', 'overview')
    op.add_column('patient_cash_transactions', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('patient_cash_transactions', 'overview')
    op.add_column('patient_bank_transactions', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('patient_bank_transactions', 'overview')
    op.create_table('transaction_genres',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='transaction_genres_pkey'),
    sa.UniqueConstraint('name', name='transaction_genres_name_key')
    )
    # ### end Alembic commands ###
