"""update finance models

Revision ID: c7fe1b60eacd
Revises: 652a9b47dc3d
Create Date: 2023-02-08 15:12:19.541040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7fe1b60eacd'
down_revision = '652a9b47dc3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('acc_number', sa.String(), nullable=False),
    sa.Column('overview', sa.String(), nullable=True),
    sa.Column('credit', sa.Integer(), nullable=True),
    sa.Column('debit', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('acc_number'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cashdesks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('overview', sa.String(), nullable=True),
    sa.Column('credit', sa.Integer(), nullable=True),
    sa.Column('debit', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('transaction_genres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bank_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('overview', sa.String(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('paid', sa.Integer(), nullable=True),
    sa.Column('due', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('bank_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['transaction_genres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cash_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('overview', sa.String(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('paid', sa.Integer(), nullable=True),
    sa.Column('due', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('cashdesk_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cashdesk_id'], ['cashdesks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['transaction_genres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('overview', sa.String(), nullable=True),
    sa.Column('inssurance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inssurance_id'], ['insurances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('insurance_tiers', sa.Column('ceiling', sa.Float(), nullable=False))
    op.add_column('insurance_tiers', sa.Column('custom_price', sa.Float(), nullable=False))
    op.add_column('insurances', sa.Column('overview', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'insurances', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'insurances', type_='unique')
    op.drop_column('insurances', 'overview')
    op.drop_column('insurance_tiers', 'custom_price')
    op.drop_column('insurance_tiers', 'ceiling')
    op.drop_table('companies')
    op.drop_table('cash_transactions')
    op.drop_table('bank_transactions')
    op.drop_table('transaction_genres')
    op.drop_table('cashdesks')
    op.drop_table('banks')
    # ### end Alembic commands ###
