"""add rx and admission relationships

Revision ID: dc2ee3313e01
Revises: 257ecba9249c
Create Date: 2022-10-24 18:57:24.141953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc2ee3313e01'
down_revision = '257ecba9249c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admissions', sa.Column('doctor_id', sa.Integer(), nullable=True))
    op.add_column('admissions', sa.Column('patient_id', sa.Integer(), nullable=True))
    op.add_column('admissions', sa.Column('room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'admissions', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'admissions', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'admissions', 'users', ['doctor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admissions', type_='foreignkey')
    op.drop_constraint(None, 'admissions', type_='foreignkey')
    op.drop_constraint(None, 'admissions', type_='foreignkey')
    op.drop_column('admissions', 'room_id')
    op.drop_column('admissions', 'patient_id')
    op.drop_column('admissions', 'doctor_id')
    # ### end Alembic commands ###
