"""update appointment model

Revision ID: eb14391dba1e
Revises: 03b063afb32e
Create Date: 2022-12-07 20:24:13.654613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb14391dba1e'
down_revision = '03b063afb32e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'day',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('appointments', 'time',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'time',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('appointments', 'day',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
