"""add user-role relationship

Revision ID: f1c9de1cf332
Revises: d8e8eb05d75e
Create Date: 2022-10-22 18:17:50.071827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1c9de1cf332'
down_revision = 'd8e8eb05d75e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'roles', ['id'])
    op.create_unique_constraint(None, 'subroles', ['id'])
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.drop_constraint(None, 'subroles', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    # ### end Alembic commands ###
